// Generated by CoffeeScript 1.7.1
(function() {
  var convertToTimestamp, root, sanitizeData, validator;

  validator = require('validator');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.parseAndFixActivity = function(input) {
    var qa;
    if (input.updatedAt === void 0) {
      if (input.other_date === void 0) {
        input.updatedAt = new Date().getTime().toString();
      } else {
        input.updatedAt = convertToTimestamp(input.other_date);
        delete input.other_date;
      }
    }
    if (input.units === void 0) {
      if (input.quantity !== void 0) {
        qa = input.quantity.split(" ");
        if (qa.length > 1 && parseInt(qa[0]) > 0) {
          input.quantity = qa[0];
          input.units = qa[1];
        }
      }
    }
    input.type = 'activity';
    return sanitizeData(input);
  };

  sanitizeData = function(activity) {
    if (activity.action != null) {
      activity.action = validator.escape(activity.action);
    }
    if (activity.category != null) {
      activity.category = validator.escape(activity.category);
    }
    if (activity.updatedAt != null) {
      activity.updatedAt = validator.escape(activity.updatedAt);
    }
    if (activity.units != null) {
      activity.units = validator.escape(activity.units);
    }
    if (activity.quantity != null) {
      activity.quantity = validator.escape(activity.quantity);
    }
    return activity;
  };

  convertToTimestamp = function(strdt) {
    var d;
    d = new Date(strdt);
    d.setHours(12);
    if (d === 'Invalid Date') {
      d = new Date();
    }
    return d.getTime().toString();
  };

}).call(this);
